# qwerty-layout
keycode  16 = q
keycode  17 = w
keycode  18 = l
keycode  19 = d
keycode  20 = g
keycode  21 = j
keycode  22 = y
keycode  23 = o
keycode  24 = u
#
keycode  30 = n
keycode  31 = r
keycode  32 = s
keycode  33 = t
keycode  34 = m
keycode  35 = f
keycode  36 = h
keycode  37 = e
keycode  38 = i
keycode  39 = a
#
keycode  44 = z
keycode  45 = x
keycode  46 = c
keycode  47 = v
keycode  48 = b
keycode  49 = k
keycode  50 = p
#
include "compose"
